version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
        - VITE_API_URL=${API_URL:-http://localhost:8000}
        - VITE_AUTH_DOMAIN=${AUTH_DOMAIN:-auth.local}
        - VITE_DEV_SERVER_PORT=3000
    ports:
      - "3000:3000"  # Main application port
      - "9229:9229"  # Node.js debugging port
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${API_URL:-http://localhost:8000}
      - VITE_AUTH_DOMAIN=${AUTH_DOMAIN:-auth.local}
      - VITE_ENABLE_MOCK_API=${ENABLE_MOCK_API:-false}
      - VITE_ENABLE_DEBUG=${ENABLE_DEBUG:-true}
      - VITE_LOG_LEVEL=${LOG_LEVEL:-debug}
      # Enable file watching for development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # Vite specific settings
      - VITE_PORT=3000
      - VITE_HMR_PORT=24678
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    init: true
    networks:
      - pa-network
    depends_on: []  # Add backend services when needed

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules

networks:
  pa-network:
    name: pa-network
    driver: bridge
    enable_ipv6: false
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: pa-dev-net
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

x-develop:
  web:
    watch:
      - action: sync
        path: ./src
        target: /app/src
        ignore:
          - node_modules/
          - dist/
          - coverage/
          - .git/
      - action: rebuild
        path: package.json
      - action: rebuild
        path: package-lock.json
    develop:
      watch:
        - action: sync+restart
          path: vite.config.ts
          target: /app/vite.config.ts